#!/bin/bash
# make sure this container is started as privileged, and has the following volumes bind mounted in
#	- /proc:/host/proc
#       - /var/run/convoy:/var/run/convoy
#       - /storage

set -e

sleep 30

get_metadata() {
    echo $(curl -s http://rancher-metadata/latest/services/convoy-gluster/metadata/$1)
}

GLUSTER_STACK_NAME=$(get_metadata gluster_stack)
STACK_NAME=$(curl -s http://rancher-metadata/latest/self/stack/name)
SERVICE_NAME=$(get_metadata gluster_service)
VOLUME_POOL=$(get_metadata volume_pool)

CONVOY_SOCK=/var/run/convoy/$STACK_NAME.sock

HOST_UUID=$(curl -s http://rancher-metadata/latest/self/host/uuid)

nsenter --mount=/host/proc/1/ns/mnt /bin/bash -c "\
    add-apt-repository ppa:gluster/glusterfs-3.7 && apt-get update && \
    apt-get install -y --no-install-recommends \
        openssh-server \
        vim \
        wget \
        software-properties-common \
        glusterfs-client"

convoy --socket $CONVOY_SOCK daemon --mnt-ns /host/proc/1/ns/mnt \
    --drivers glusterfs \
    --driver-opts glusterfs.rancherstack=$GLUSTER_STACK_NAME \
    --driver-opts glusterfs.rancherservice=$SERVICE_NAME \
    --driver-opts glusterfs.defaultvolumepool=$VOLUME_POOL &
echo "unix://$CONVOY_SOCK" > /etc/docker/plugins/$STACK_NAME.spec

exec convoy-agent \
    --url $CATTLE_URL \
    --access-key $CATTLE_ACCESS_KEY \
    --secret-key $CATTLE_SECRET_KEY \
    --storagepool-driver $STACK_NAME \
    volume \
    --socket $CONVOY_SOCK \
    --host-uuid $HOST_UUID
