#!/bin/bash

set -e

cd $(dirname $0)/..

mkdir -p ./build

install_go()
{
	# Taken from Google/golang Dockerfile...
	apt-get update -y && apt-get install --no-install-recommends -y -q curl build-essential \
		ca-certificates git mercurial bzr
	mkdir /goroot && curl https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz | tar xvzf - -C /goroot --strip-components=1
	echo $PWD
	echo "export GOROOT=\"/goroot\"" > ./build/bootstrap.envs
	echo "export PATH=\"$PATH:/goroot/bin\"" >> ./build/bootstrap.envs
}

install_convoy()
{
	tmpdir=$(mktemp -d)
	pushd $tmpdir
	curl -sSL -o convoy.tar.gz https://github.com/rancher/convoy/releases/download/v0.4.4-rc2/convoy.tar.gz
	tar -xzvf convoy.tar.gz && cp ./convoy/convoy /usr/bin
	popd
	rm -rf ${tmpdir}
}

if [ ! $(command -v go) ]; then
	echo "Going to try installing Go..."
	install_go
fi

install_convoy
