#!/bin/bash

set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo Current building version is $VERSION

. ./scripts/common_functions
set_project_vars

GITCOMMIT=`git rev-parse --short HEAD`

if [ -L ${PACKAGE} ]; then
    rm ${PACKAGE}
fi

if [ ! -e ${PACKAGE} ]; then
    mkdir -p $(dirname $PACKAGE)
    ln -s $(pwd) $PACKAGE
fi

rm -rf bin
mkdir -p bin
CGO_ENABLED=0 go build -o bin/${PROJECT} -a -installsuffix cgo -ldflags \
        "-extldflags -static -X main.VERSION=$VERSION"
