#!/bin/bash

set -e

source $(dirname $0)/version

cd $(dirname $0)/..

TARGET="dist/artifacts/convoy-agent.tar.gz"
tar -xvf ${TARGET} -C dist/artifacts/

rm -rf dist/build
mkdir -p dist/build/convoy-agent
cp dist/artifacts/convoy-agent dist/build/convoy-agent
cp packaging/convoy-agent/* dist/build/convoy-agent

TAG=${TAG:-${VERSION}}
REPO=${REPO:=rancher}

echo "Building Docker image ${REPO}/convoy-agent:${TAG}"
docker build --rm -t ${REPO}/convoy-agent:${TAG} dist/build/convoy-agent
echo "Finished building Docker image ${REPO}/convoy-agent:${TAG}"
