#!/bin/bash

cd $(dirname $0)/..

. ./scripts/common_functions

set_project_vars

rm -rf dist
mkdir -p dist/artifacts

cd build
echo "Packaging:"
tar czf ../dist/artifacts/$PROJECT.tar.gz .
echo Created dist/artifacts/$PROJECT.tar.gz
