#!/bin/bash

set -e

cd $(dirname $0)/..

. ./scripts/common_functions

set_project_vars

convoy daemon --drivers vfs --driver-opts vfs.path=$(pwd) 1>/dev/null &

mkdir -p tests/.healthcheck
mkdir -p tests/.healthcheck2
mkdir -p tests/.root

echo '1234567890' > tests/.root/UUID

go test -p 1 -timeout 99999s ./...

result=$(find . -name "*.go" | grep -v ./vendor | xargs gofmt -s -l)
if [ -n "$result" ]; then
    echo "${#result[@]} files failed gofmt check:"
fi
for i in $result; do
    echo $i
done

[ -n "$result" ] && exit 1

echo OK
