#!/bin/sh

set -e

sleep 10

HEALTHCHECK_TYPE="metadata"

STACK_NAME=$(curl -s http://rancher-metadata/latest/self/stack/name)

exec convoy-agent \
	-d \
	--url $CATTLE_URL \
	--access-key $CATTLE_ACCESS_KEY \
	--secret-key $CATTLE_SECRET_KEY \
	--storagepool-driver $STACK_NAME \
	storagepool \
	--storagepool-healthcheck-type $HEALTHCHECK_TYPE
